spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:mongodb+srv://pawan6186:AKNQzcWBpaYJ3aaW@cluster0.vx89hdm.mongodb.net/?retryWrites=true&w=majority}
      auto-index-creation: true
      database: address
  application:
    name: address-management
springdoc:
  pathsToMatch: /api/**
server:
  port: 8082
eureka:
  instance:
    hostname: localhost